services:
  db:
    image: postgres:15-alpine
    container_name: ramazon_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ramazon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ramazon_pass}
      POSTGRES_DB: ${POSTGRES_DB:-ramazon_db}
    ports:
      - "5433:5432"

  bot:
    build: .
    container_name: ramazon_bot
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMINS: ${ADMINS}
      WEBHOOK_HOST: ${WEBHOOK_HOST}
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-ramazon}:${POSTGRES_PASSWORD:-ramazon_pass}@db:5432/${POSTGRES_DB:-ramazon_db}
    ports:
      - "8080:8080"

volumes:
  postgres_data:
